application: yongboy8
version: 4
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /exception
  static_dir: exception
  
- url: /reply/.*
  script: reply.py

- url: /tags/.*
  script: tags.py

- url: /.*
  script: blog.py
